### ISSUE TITLE
'TileJobInfo' object has no attribute 'tilesize'

### ISSUE THREAD

**Issue by oysteins10** [tehamalab/gdal2tiles#14]
* gdal2tiles version: 0.1.7
* GDAL version: 2.4.0
* Python version: 3.8
* Operating System: Ubuntu18.04

### Description

Hello! I'm generating a superoverlay for kml document. And there's an attribute error that shows up. I assume its a typing mistake.

### What I Did

```
gdal2tiles.generate_tiles(src_img, dest, profile='raster', kml=True)
```
And the the traceback:
```
Traceback (most recent call last):
  File "/opt/project/_test_kmz_gen.py", line 111, in _test_correlation_report
    create_super_overlay(ground_overlay_fp, superoverlay_dest)
  File "/opt/project/report/imageutils.py", line 542, in create_super_overlay
    gdal2tiles.generate_tiles(src_img, dest, profile='raster', kml=True)
  File "/code/venv/lib/python3.8/site-packages/gdal2tiles/gdal2tiles.py", line 2940, in generate_tiles
    single_threaded_tiling(input_file, output_folder, **options)
  File "/code/venv/lib/python3.8/site-packages/gdal2tiles/gdal2tiles.py", line 2826, in single_threaded_tiling
    create_base_tile(conf, tile_detail)
  File "/code/venv/lib/python3.8/site-packages/gdal2tiles/gdal2tiles.py", line 1046, in create_base_tile
    f.write(generate_kml(
  File "/code/venv/lib/python3.8/site-packages/gdal2tiles/gdal2tiles.py", line 541, in generate_kml
    args['south'], args['west'], args['north'], args['east'] = tileswne(tx, ty, tz)
  File "/code/venv/lib/python3.8/site-packages/gdal2tiles/gdal2tiles.py", line 2787, in rastertileswne
    west = tile_job_info.out_geo_trans[0] + x * tile_job_info.tilesize * pixelsizex
AttributeError: 'TileJobInfo' object has no attribute 'tilesize'
```
TileJobInfo.tile_size is the correct attribute.

**Comment by machakux** [comment]
@oysteins10 thank you very much for reporting the issue.

I hope the issue has been fixed in the latest release (0.1.8). bad97f0f49cb0eba557004f9c4007205381949b7
