### ISSUE TITLE
undefined symbol error

### ISSUE THREAD

**Issue by ismaildervisoglu** [tehamalab/gdal2tiles#3]
* gdal2tiles version: 0.1.5
* GDAL version: 2.3.1
* Python version: 3.6
* Operating System: Centos 7.4

### Description
I am getting this error : 

ImportError: /home/cisarge/temp.cisarge.com/data-vis/data-vis-libs/lib/python3.6/site-packages/osgeo/_gdal.cpython-36m-x86_64-linux-gnu.so: undefined symbol: GDALDatasetTestCapability

**Comment by machakux** [comment]
@ismaildervisoglu apologies for the late response.

What were you trying to do?  Can you share a full stacktrace and may be a code snippet that caused the error.

**Comment by ismaildervisoglu** [comment]
error occurs when import code is running


Traceback (most recent call last):
  File "flask-live-chart.py", line 11, in <module>
    from view import heatMap
  File "/home/cisarge/temp.cisarge.com/live-charts/view.py", line 16, in <module>
    import gdal2tiles
  File "/home/cisarge/temp.cisarge.com/live-charts/live-chart-example/lib/python3.6/site-packages/gdal2tiles/__init__.py", line 10, in <module>
    from .gdal2tiles import *  # noqa
  File "/home/cisarge/temp.cisarge.com/live-charts/live-chart-example/lib/python3.6/site-packages/gdal2tiles/gdal2tiles.py", line 57, in <module>
    from osgeo import gdal
  File "/home/cisarge/temp.cisarge.com/live-charts/live-chart-example/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/cisarge/temp.cisarge.com/live-charts/live-chart-example/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/cisarge/temp.cisarge.com/live-charts/live-chart-example/lib64/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/cisarge/temp.cisarge.com/live-charts/live-chart-example/lib64/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/cisarge/temp.cisarge.com/live-charts/live-chart-example/lib/python3.6/site-packages/osgeo/_gdal.cpython-36m-x86_64-linux-gnu.so: undefined symbol: GDALDatasetTestCapability
